---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 23.01.2020 20:11
function InitUnitDeath()
	local gg_trg_DEADGUI = CreateTrigger()
	TriggerRegisterAnyUnitEventBJ(gg_trg_DEADGUI, EVENT_PLAYER_UNIT_DEATH)
	TriggerAddAction(gg_trg_DEADGUI, function()

		local DeadUnit=GetTriggerUnit()--умерший
		local Killer=GetKillingUnit()--убийца
		--print("EventDead "..GetUnitName(DeadUnit).." "..GetUnitName(Killer))


		if IsUnitType(DeadUnit,UNIT_TYPE_HERO) then --герой умер
			CreateCallingBar(DeadUnit,10,"Воскрешение")
			local PD=GetOwningPlayer(DeadUnit)
			TimerStart(CreateTimer(), 10, false, function()
				ReviveHero(DeadUnit,GetPlayerStartLocationX(PD),GetPlayerStartLocationY(PD),true)
				SelectUnitForPlayerSingle(DeadUnit,PD)
				SetCameraPosition(GetPlayerStartLocationX(PD),GetPlayerStartLocationY(PD))
			end)
		end


	end)
end