---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 03.06.2020 19:27
---


function FrameBigSize( FrameTexture,secShow,i2,bonus)
	local size = 0
	local sec = 0
	local i = 1
	local turn = true
	local next = 0.039
	local  fh = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetSize(fh,next,next)
	BlzFrameSetTexture(fh, FrameTexture, 0, true)
	--local firsBonus=SubString(bonus,0,1)
	--print(firsBonus)

	--[[local  fh1 = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetSize(fh1,next/2,next/2)
	BlzFrameSetTexture(fh1, "AdmiralAssets\\DDSSymbols\\"..firsBonus, 0, true)
	local  fh2 = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetSize(fh2,next/2,next/2)
	BlzFrameSetTexture(fh2, "AdmiralAssets\\DDSSymbols\\0", 0, true)]]

	local CBPoz=BlzGetFrameByName("CommandButton_"..i2, 0) -- CommandButton_0
	BlzFrameSetPoint(fh,FRAMEPOINT_CENTER,CBPoz,FRAMEPOINT_CENTER,0,0)
	--BlzFrameSetPoint(fh1,FRAMEPOINT_CENTER,CBPoz,FRAMEPOINT_CENTER,-0.005,0)
	--BlzFrameSetPoint(fh2,FRAMEPOINT_CENTER,CBPoz,FRAMEPOINT_CENTER,0.005,0)
	--BlzFrameSetAbsPoint(fh,FRAMEPOINT_CENTER,0.4,0.1)
	local newText = BlzCreateFrameByType("TEXT", "ButtonChargesText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetText(newText,bonus)
	BlzFrameSetPoint(newText,FRAMEPOINT_CENTER,CBPoz,FRAMEPOINT_CENTER,0,0)



	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		sec = sec + TIMER_PERIOD
		size = size + (i * 0.005)

		--print(sec)
		if sec >= secShow and turn then
			--print("off")
			turn = false
			i = i * (-1)
		end
		if size <= 0 then
			DestroyTimer(GetExpiredTimer())
			BlzDestroyFrame(fh)
			--BlzDestroyFrame(fh1)
			--BlzDestroyFrame(fh2)
			BlzDestroyFrame(newText)
			size = 0
		end

		--BlzFrameSetAbsPoint(fh, FRAMEPOINT_CENTER, 0.1 + next * (index - 1), 0.02 + size / 4)
	--	print(size.." "..i)
		BlzFrameSetSize(fh,next+size,next+size)
		BlzFrameSetScale(newText,(next+size)*50)
		--BlzFrameSetSize(fh1,next+size/2,next+size/2)
		--BlzFrameSetSize(fh2,next+size/2,next+size/2)
		--BlzFrameSetSize(newText,next+size,next+size)
	end)
end