---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 27.05.2020 16:53
---

function GetUnitGreenAttackBonus(hero)
		local bonus=0
		if IsUnitSelected(hero,GetOwningPlayer(hero)) then
			local frame=BlzGetFrameByName("InfoPanelIconValue",0)
			local text=BlzFrameGetText(frame) --"46 - 56 |CFF00FF00+12|R"
			if string.len(text)>=15 then
				bonus =  text:sub(text:find("|C")+10,-3)
			end
			bonus=tonumber(bonus)
		end
		return bonus
end

function SetUnitGreenAttackBonus(hero,bonusSet)
	local bonus=0
	local frame=BlzGetFrameByName("InfoPanelIconValue",0)
	local data=HERO[GetPlayerId(GetOwningPlayer(hero))]
	data.AttackOriginal=BlzFrameGetText(frame)
	if IsUnitSelected(hero,GetOwningPlayer(hero)) then

		local text=BlzFrameGetText(frame) --"46 - 56 |CFF00FF00+12|R"
		if string.len(text)>=15 then
			bonus =  text:sub(text:find("|C")+10,-3)
		end
		bonus=tonumber(bonus)
		if bonus==bonusSet then return end
		local totalBonus=bonus+bonusSet
		local whiteText=text
		if bonus~=0 then
			 whiteText=text.sub(text,0,-(4+string.len(totalBonus)))
		end
		print("white" ..whiteText)
		if totalBonus>0 then
			BlzFrameSetText(frame,whiteText.."|CFF00FF00+"..totalBonus.."|R")
		end

	end
	--return bonus
end


