---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 24.06.2020 13:08
---
function CreateCooldownIndicator(x,y)
	local cd= BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
	BlzFrameSetTexture(cd, "DDS512".."\\0000000", 0, true)
	--BlzFrameSetVertexColor(cd,BlzConvertColor(255,0,0,128))
	BlzFrameSetAlpha(cd,128)
	BlzFrameSetSize(cd, NextPoint, NextPoint)
	BlzFrameSetAbsPoint(cd, FRAMEPOINT_CENTER,x , y)
	return cd
end

function StarFrameCooldown(cdFrame,cd)
	local amount=(0.05*1024)/cd
	print(amount)
	local full=0
	cdFrame=CreateCooldownIndicator(0.637,0.113)
	local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", cdFrame, "", 0)
	BlzFrameSetText(text, cd)
	BlzFrameSetPoint(text, FRAMEPOINT_CENTER, cdFrame, FRAMEPOINT_CENTER, 0.,0.)
	BlzFrameSetScale(text,1.5)
	BlzFrameSetAlpha(text,255)
	local sec=cd
	TimerStart(CreateTimer(), 0.05, true, function()
		full=full+amount
		sec=sec-0.05
		BlzFrameSetText(text,string.format("%%02.1f",sec))

		--print(tonumber(sec)/100.)
		--BlzFrameSetValue(cdFrame, full)
		--print(Zero4(full))
		BlzFrameSetTexture(cdFrame, "DDS512".."\\000"..Zero4(R2I(full+amount)), 0, true)
		if full>1023 then
			DestroyTimer(GetExpiredTimer())
			BlzDestroyFrame(cdFrame)
			full=0
		end
	end)
end

function Zero4(s)
	local ns=""
	if string.len(s)==1 then
		ns="000"..s
	elseif string.len(s)==2 then
		ns="00"..s
	elseif string.len(s)==3 then
		ns="0"..s
	else
		ns=s
	end
	return ns
end