---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 24.06.2020 13:08
---
function CreateCooldownIndicator(data)
	local cd= BlzCreateFrameByType("BACKDROP", "Face", data.SelfFrame, "", 0)
	BlzFrameSetTexture(cd, "DDS512".."\\0000000", 0, true)
	BlzFrameSetAlpha(cd,128)
	BlzFrameSetSize(cd, NextPoint, NextPoint)
	BlzFrameSetAbsPoint(cd, FRAMEPOINT_CENTER,data.PosX,data.PosY)
	return cd
end

function StarFrameCooldown(data,cd)
	if data.Timer then
		EndFrameCD(data)
	end
	local frameCount=1024
	data.PercentAmount=(0.05*frameCount)/cd
	data.Full=0
	data.CdIndicatorFrame=CreateCooldownIndicator(data)
	data.OnCD=true
	data.CurrentCDTime=cd
	data.CurrentCD=cd
	data.Timer=CreateTimer()
	TimerStart(data.Timer, 0.05, true, function()
		if not data.OnPaused then
			data.Full=data.Full+data.PercentAmount
			data.CurrentCDTime=data.CurrentCDTime-0.05
		end
		BlzFrameSetText(data.SelfFrame, string.format("%%02.1f",data.CurrentCDTime))
		BlzFrameSetTexture(data.CdIndicatorFrame, "DDS512".."\\000"..Zero4(R2I(data.Full+data.PercentAmount)), 0, true)
		if data.Full>frameCount-1 then
			EndFrameCD(data)
		end
	end)
end

function Zero4(s)
	local ns=""
	if string.len(s)==1 then
		ns="000"..s
	elseif string.len(s)==2 then
		ns="00"..s
	elseif string.len(s)==3 then
		ns="0"..s
	else
		ns=s
	end
	return ns
end

function PauseFrameCD(data,isPaused)  --true - пауза, false - продолжить
	if isPaused then
		data.OnPaused=true
	else
		data.OnPaused=false
	end
end

function EndFrameCD(data)
	DestroyTimer(data.Timer)
	BlzFrameSetText(data.SelfFrame, "")
	data.Timer=nil
	BlzDestroyFrame(data.CdIndicatorFrame)
	data.Full=0
	data.OnCD=false
end

function AddSpeedToFrameCD(data,sec)
	data.CurrentCDTime=data.CurrentCDTime-sec
	data.Full=data.Full+(2*sec*data.CurrentCD*data.PercentAmount)
end



function CreateAbilityFrame(mainData,pos,texture,type,HotKeyPos) -- позиция 1 - 12
	local data=mainData.FrameTable[pos]
	data.HotKeyPos=HotKeyPos -- выставление индекса
	CreateAbilityToolTip(mainData,data)-- создание тултипа
	if not texture then
		texture="ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn"
	end

	--data.SelfFrame = BlzCreateFrameByType("GLUETEXTBUTTON", "MyButton", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "ScriptDialogButton", 0)

	data.SelfFrame = BlzCreateFrame("GlueWText", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)
	--data.IconFrame = BlzCreateFrameByType("BACKDROP", "FaceButtonIcon", data.SelfFrame, "", 0)
	data.IconFrame = BlzFrameGetChild(data.SelfFrame, 0)
	BlzFrameSetTexture(data.IconFrame, texture, 0, true)
	BlzFrameSetText(BlzFrameGetChild(data.SelfFrame, 2), "")
	--BlzFrameSetText(data.SelfFrame, [[text]])

	BlzFrameSetAllPoints(data.IconFrame, data.SelfFrame)
	--BlzFrameSetTexture(data.IconFrame, texture, 0, true)
	BlzFrameSetSize(data.SelfFrame,NextPoint,NextPoint)
	BlzFrameSetAbsPoint(data.SelfFrame,FRAMEPOINT_CENTER,data.PosX,data.PosY)
	--print(type)
	if type=="active" then
		--print("создана ативная кнопка")
		local  ClickTrig = CreateTrigger()
		BlzTriggerRegisterFrameEvent(ClickTrig, data.SelfFrame, FRAMEEVENT_CONTROL_CLICK)
		TriggerAddAction(ClickTrig, function ()
			--print("Нажата кнопка "..pos)
			BlzFrameSetEnable(BlzGetTriggerFrame(), false)
			BlzFrameSetEnable(BlzGetTriggerFrame(), true)
			if not data.OnCD then
				if pos==10 then --перезарядка огнемёта
					StarFrameCooldown(data,10)
					mainData.FirePillarState=true
					StartFirePillar(mainData)
				end
				if pos==11 then -- старт кактусов
					if CustomAbilityIsReady(mainData,data) and not mainData.StartDrawing then
						EatingCactus(mainData)
						mainData.StartDrawing=true
						mainData.DestroyDrawing=false
					end
				end
			end
		end)
	end


	if mainData.CustomAbilities[HotKeyPos].MaxCharges then
		data.Charges=mainData.CustomAbilities[HotKeyPos].MaxCharges-50
		--print(data.Charges)
		data.ChargesFrame= BlzCreateFrameByType("BACKDROP", "Face",data.SelfFrame, "", 0)
		data.ChargesFrameText = BlzCreateFrameByType("TEXT", "ButtonChargesText", data.ChargesFrame, "", 0)
		BlzFrameSetTexture(data.ChargesFrame, "UI\\Widgets\\Console\\Human\\CommandButton\\human-button-lvls-overlay", 0, true)
		BlzFrameSetSize(data.ChargesFrame, 0.02, 0.015)
		--BlzFrameSetAbsPoint(data.ChargesFrame, FRAMEPOINT_CENTER,0.4+0.02 , 0.6-0.02)
		BlzFrameSetPoint(data.ChargesFrame, FRAMEPOINT_BOTTOMRIGHT, data.SelfFrame, FRAMEPOINT_BOTTOMRIGHT, 0,0)
		BlzFrameSetText(data.ChargesFrameText, data.Charges)
		BlzFrameSetPoint(data.ChargesFrameText, FRAMEPOINT_CENTER, data.ChargesFrame, FRAMEPOINT_CENTER, 0.,0.)
		if HotKeyPos==3 then
			TimerStart(CreateTimer(), 1, true, function()
				if data.Charges<mainData.CustomAbilities[HotKeyPos].MaxCharges then
					data.Charges=data.Charges+1
				end
			end)
			TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
				BlzFrameSetText(data.ChargesFrameText, data.Charges)
				--print(GetHandleId(data.ChargesFrameText))
			end)

		end
	end

	local  TrigMOUSE_ENTER = CreateTrigger()
	BlzTriggerRegisterFrameEvent( TrigMOUSE_ENTER, data.SelfFrame, FRAMEEVENT_MOUSE_ENTER)
	TriggerAddAction( TrigMOUSE_ENTER, function ()
		--print("показать подсказку")
		ShowAbilityTooltip(mainData,data,true)
		data.MouseOnFrame=true
		local pid=GetPlayerId(GetTriggerPlayer())
		--print(GetUnitName())
		if data.Number==9 then--радиус для уворота
			CreateVisualMarkerRadius(data,250,HERO[pid].UnitHero)
		end
		if data.Number==10 then--радиус огнемёта
			CreateVisualMarkerRadius(data,800,HERO[pid].UnitHero,nil,nil,data.Number)
		end
	end)
	local  TrigMOUSE_LEAVE = CreateTrigger()
	BlzTriggerRegisterFrameEvent( TrigMOUSE_LEAVE, data.SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
	TriggerAddAction( TrigMOUSE_LEAVE, function ()
		data.MouseOnFrame=false
		HideAllToolTips(mainData)
		--print("убрать подсказку")
	end)


end

function HideAllCustomAbility(data,isHide)
	--print("первый вызов")
	if isHide then
		for i=1,12 do
			BlzFrameSetVisible(data.FrameTable[i].SelfFrame,false)
		end
	else
		for i=1,12 do
			if GetLocalPlayer()==Player(data.pid) then
				BlzFrameSetVisible(data.FrameTable[i].SelfFrame,true)
			end
		end
	end
end

function CreateVisualMarkerRadius (data,radius,hero,x,y,number)
	if hero then
		--print(GetUnitName(hero))
		--x,y=GetUnitXY(hero)
	end
	-- circle_fill
	local path="circ"
	path="replaceabletextures\\selection\\rangeindicator"
	if number==10 then
	--	path="circle_fill"
	end

	local CircleImage=CreateImage(path,radius,radius,radius,OutPoint,OutPoint,0,0,0,0,4)
	SetImageRenderAlways(CircleImage, true)
	ShowImage(CircleImage,false)

	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		local xs,ys=GetUnitX(hero)-radius/2-16,GetUnitY(hero)-radius/2-16
		SetImagePosition(CircleImage,xs,ys,0)
		if GetLocalPlayer()==GetOwningPlayer(hero) then
			ShowImage(CircleImage,true)
		end
		if not data.MouseOnFrame then
			SetImagePosition(CircleImage,OutPoint,OutPoint,0)
			DestroyImage(CircleImage)
			DestroyTimer(GetExpiredTimer())
		end
	end)
end

function  UnitHaveReadyAbility(hero,abiID)
	local isReady=false
	if GetUnitAbilityLevel(hero,abiID)>0
			and BlzGetUnitAbilityCooldownRemaining(hero,abiID)<=.01
			and UnitAlive(hero)
			and GetUnitState(hero,UNIT_STATE_MANA)>=BlzGetUnitAbilityManaCost(hero,abiID,GetUnitAbilityLevel(hero,abiID)-1)
			and IsUnitSelected(hero,GetOwningPlayer(hero))
	then
		isReady=true
	end
	return isReady
end