---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 29.06.2020 23:06
---
cactusModel="Doodads\\Barrens\\Plants\\Cactus\\Cactus".."" --0-9
function EatingCactus(mainData)
	print("курсор превращается в кактус")
	local r=GetRandomInt(0,9)
	local eff=AddSpecialEffect(cactusModel..r,GetPlayerMouseX[mainData.pid],GetPlayerMouseY[mainData.pid])
	BlzSetSpecialEffectYaw(eff,math.rad(GetRandomReal(0,360)))
	TimerStart(CreateTimer(), TIMER_PERIOD, true, function()
		local x,y=GetPlayerMouseX[mainData.pid],GetPlayerMouseY[mainData.pid]
		local z=GetTerrainZ(x,y)
		BlzSetSpecialEffectPosition(eff,x,y,z)
		if mainData.ReleaseLMB then
			DestroyTimer(GetExpiredTimer())
		end
	end)
end