---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 10.01.2020 22:05
--
---Глобалки
TIMER_PERIOD = 0.03125
HERO = {}
do
	local InitGlobalsOrigin = InitGlobals
	function InitGlobals()
		InitGlobalsOrigin()
		perebor = CreateGroup() --1 едиснвенная глобальная группа на всю игру, никакие Destroy Привет гуишники
		--InitSpellTrigger() -- Инициализация функции кастов

		KeyRegistration() -- инициализация отлова нажатия клавиш
		InitSelectionRegister() -- инициализация выбора
		InitMouseMoveTrigger() -- Запуск отслеживания положения мыши
		InitDamage()
		InitHEROTable() -- Инициализация таблицы героев
		--InitSoundsA()--Создаём звуки
		--InitUnitDeath()-- инициализация смерти
		--CreateGlue()
		TimerStart(CreateTimer(), 0, false, function()

			--Test12FrameAbility()-- фреймы
			InitMainFrameTable(HERO[0]) -- мульти создаётся здесь
		end)
	end

end

do
	-- Автоочистка таймеров
	local DestroyTimer_Original = DestroyTimer
	function DestroyTimer(whichTimer)
		PauseTimer(whichTimer)
		DestroyTimer_Original(whichTimer)
	end

end

function InitHEROTable()
	EnableDragSelect(false, false)
	if BlzLoadTOCFile("Main.toc") then
	else
		print("ошибка загрузки toc")
	end
	for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
		HERO[i] = {
			pid = i,
			UnitHero = nil,
			IsInterface = false,
			IsMainHeroOnHit = false,
			EvasionState=false,
			FirePillarState=false,
			CustomAbilities = { -- статичные данные, но менять можно и муи
				[1] = {
					Ready = true,
					CD=10,
					Name="Фазовый сдвиг",
					Description="\nПри получении урона герой смещается между пространствами и избегает этого урона а также любого последующего в течении 0.5 сек. Атаки по герою уменьшают перезарядку способности на 1 секунду"
				},
				[2] = {
					Ready = true,
					CD=15,
					Name="Огненный столб",
					Description="Выпускает поток огня впереди себя"
				},
				[3] = {
					Ready = true,
					CD=7,
					Name="Поле кактусов",
					Description="Сажает кактусы в указанной точке, сажайте кактусы по 1 или удерживайте левую кнопку мыши зажатой, для массовм посадки. Способность имеет 10 зарядов, перезарядка заряда - 7 секунд ",
					MaxCharges=10
				},
				R = {},
				S = {},
				D = {},
				F = {}
			},
			FrameTable = {-- создание таблице пустыше
				SelfFrame = nil, -- Основной фрейм
				IconFrame = nil, -- Его иконка
				CdIndicatorFrame = nil, -- Фрейм перезарядки
				ToolTip=nil, -- фрейм подскизки, общий
				Number = i,
				PosX = 0,
				PosY = 0,
				OnCD = false,
				CurrentCDTime = 0,
				Timer = nil,
				PercentAmount = 0,
				OnPaused = false,
				Full = 0,
				CurrentCD = 0,
				MouseOnFrame = false,
				HotKeyPos=0,
			},
			ReleaseQ=false,
			ReleaseW=false,
			ReleaseE=false,
			ReleaseR=false,
			ReleaseLMB=false,
			ReleaseRMB=false,
		}
	end
end


function InitMainFrameTable(data)
	--	local frames={}
	local k = 0
	local k2 = 1
	local greed = 0.0045
	for i = 1, 12 do -- заполнение таблицы пустышек
		data.FrameTable[i] = {
			SelfFrame = nil, -- Основной фрейм
			IconFrame = nil, -- Его иконка
			CdIndicatorFrame = nil, -- Фрейм перезарядки
			ToolTip=nil, -- фрейм подскизки, общий
			Number = i,
			PosX = 0,
			PosY = 0,
			OnCD = false,
			CurrentCDTime = 0,
			Timer = nil,
			PercentAmount = 0,
			OnPaused = false,
			Full = 0,
			CurrentCD = 0,
			MouseOnFrame = false,
			HotKeyPos=0,
		}
		local data2 = data.FrameTable[i]
		k = k + 1

		if k == 5 then
			k = 1
			k2 = k2 + 1
		end
		data2.PosX = 0.637 + ((NextPoint + greed) * (k - 1))
		data2.PosY = 0.113 - ((NextPoint + greed) * (k2 - 1))
	end
	return data.FrameTable
end