---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 02.06.2020 22:32
---

gg_snd_BristleBackMissileLaunch1 = nil
gg_snd_BristleBackMissileLaunch2 = nil
gg_snd_BristleBackMissileLaunch3 = nil
gg_snd_MetalHeavySliceFlesh1 = nil
gg_snd_MetalHeavySliceFlesh2 = nil
gg_snd_MetalHeavySliceFlesh3 = nil

function InitSoundsA()
	gg_snd_BristleBackMissileLaunch1 = CreateSound("Abilities/Weapons/BristleBackMissile/BristleBackMissileLaunch1.flac", false, true, true, 0, 0, "MissilesEAX")
	SetSoundParamsFromLabel(gg_snd_BristleBackMissileLaunch1, "BristleBackMissileLaunch")
	SetSoundDuration(gg_snd_BristleBackMissileLaunch1, 345)
	SetSoundVolume(gg_snd_BristleBackMissileLaunch1, 250)
	gg_snd_BristleBackMissileLaunch2 = CreateSound("Abilities/Weapons/BristleBackMissile/BristleBackMissileLaunch2.flac", false, true, true, 0, 0, "MissilesEAX")
	SetSoundParamsFromLabel(gg_snd_BristleBackMissileLaunch2, "BristleBackMissileLaunch")
	SetSoundDuration(gg_snd_BristleBackMissileLaunch2, 372)
	SetSoundVolume(gg_snd_BristleBackMissileLaunch2, 250)
	gg_snd_BristleBackMissileLaunch3 = CreateSound("Abilities/Weapons/BristleBackMissile/BristleBackMissileLaunch3.flac", false, true, true, 0, 0, "MissilesEAX")
	SetSoundParamsFromLabel(gg_snd_BristleBackMissileLaunch3, "BristleBackMissileLaunch")
	SetSoundDuration(gg_snd_BristleBackMissileLaunch3, 333)
	SetSoundVolume(gg_snd_BristleBackMissileLaunch3, 250)

	gg_snd_MetalHeavySliceFlesh1 = CreateSound("Sound/Units/Combat/MetalHeavySliceFlesh1.flac", false, true, true, 0, 0, "MissilesEAX")
	SetSoundParamsFromLabel(gg_snd_MetalHeavySliceFlesh1, "MetalHeavySliceFlesh")
	SetSoundDuration(gg_snd_MetalHeavySliceFlesh1, 1104)
	SetSoundVolume(gg_snd_MetalHeavySliceFlesh1, 250)
	gg_snd_MetalHeavySliceFlesh2 = CreateSound("Sound/Units/Combat/MetalHeavySliceFlesh2.flac", false, true, true, 0, 0, "MissilesEAX")
	SetSoundParamsFromLabel(gg_snd_MetalHeavySliceFlesh2, "MetalHeavySliceFlesh")
	SetSoundDuration(gg_snd_MetalHeavySliceFlesh2, 946)
	SetSoundVolume(gg_snd_MetalHeavySliceFlesh2, 250)
	gg_snd_MetalHeavySliceFlesh3 = CreateSound("Sound/Units/Combat/MetalHeavySliceFlesh3.flac", false, true, true, 0, 0, "MissilesEAX")
	SetSoundParamsFromLabel(gg_snd_MetalHeavySliceFlesh3, "MetalHeavySliceFlesh")
	SetSoundDuration(gg_snd_MetalHeavySliceFlesh3, 853)
	SetSoundVolume(gg_snd_MetalHeavySliceFlesh3, 250)
end
